spring:
  application:
    name: shoppingcart-ui
  config:
    import: configserver:http://localhost:8888
server:
  port: 8080
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: *
  routes:
    catalogservice:
      path: /catalog/**
      serviceId: catalog-service
    orderservice:
      path: /orders/**
      serviceId: order-service